### ISSUE TITLE
Custom events changes unsaved

### ISSUE THREAD

**Issue by aeroelectrolight** [BitsAndDroids/FlightConnector-Rust#277] opened 2024-11-14 22:46 UTC
**Describe the bug**
The Save button for custom events does not save changes. I managed to save once by accident but couldn't do it again.

**To Reproduce**
When I make a modification, it appears in the "custom events" menu but if I change the menu and return to the "custom events" menu, it is in the same state as before the modification.
I don't understand why ? 

Thank you so much
Ludo

**Comment by BitsAndDroids** [comment] 2024-11-14 23:00
It might be that the connector loads the default events (Id < 3000) again. Are you experiencing the same with events that have an id bigger than 3000? Will report back tomorrow with my findings.

**Comment by BitsAndDroids** [comment] 2024-11-15 17:30
Hmm I found a bug where saving an event could cause the id to be saved as text instead of a number. Fixed that and will release a small patch for that. But that couldn't explain the behavior you are experiencing since it would prevent the events from loading. Could you perhaps use the report a bug button in the connector (the lower right corner)? This will send the events you've made to me so I could investigate this further.

**Comment by BitsAndDroids** [comment] 2024-11-15 17:31
Nevermind wrote the previous comment too soon. all fields seem to save except for the id. Saving that one doesn't work for some reason. Will report back when I found more.

**Comment by BitsAndDroids** [comment] 2024-11-15 20:20
Found the issue. The save was wired to update an event which looked for an id in all events to update. If somebody changed the id it needed to create a new event but the connector started to look for an existing event with the new id. This should be fixed in 0.9.2 (out in a few minutes). Please let me know if this fixed the issue for you.

**Comment by BitsAndDroids** [comment] 2024-11-16 10:15
You are right. Thanks for that video. It helped pinpoint the problem.  The problem arises when navigating away from the window and opening it again. For some reason, the app currently loses the location of the event store when doing this. Will report back when I've found a solution.

**Comment by BitsAndDroids** [comment] 2024-11-16 15:17
Once again thank you very much. I've found the cause and it's fixed in version 0.9.3

**Comment by aeroelectrolight** [comment] 2024-11-16 17:33
Yeah, that's work fine.
Great work ! 
Thanks a lot.

**Closed** 2024-11-16 19:12 UTC
Labels: bug
